services:
  lgtm:
    image: grafana/otel-lgtm:0.29.1
    ports:
      - "3000:3000"
      - "3100:3100"
      - "4318:4318"
    volumes:
      - ./otel-collector-config.yaml:/otel-lgtm/otelcol-config.yaml:ro
      - lgtm-data:/data

volumes:
  lgtm-data:
