receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - http://localhost:5173

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
    path: /ready

exporters:
  otlp_http/logs:
    endpoint: http://127.0.0.1:3100/otlp
    sending_queue:
      batch: {}
  otlp_http/traces:
    endpoint: http://127.0.0.1:4418
    sending_queue:
      batch: {}

service:
  extensions: [health_check]
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [otlp_http/logs]
    traces:
      receivers: [otlp]
      exporters: [otlp_http/traces]
