receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - http://localhost:5173
            - http://127.0.0.1:5173

processors:
  batch: {}

exporters:
  otlphttp/lgtm:
    endpoint: http://lgtm:4318

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/lgtm]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/lgtm]
