[package]
name = "multicast-in-rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socket2 = { version = "0.3.4", features = ["reuseport"] }
once_cell = "1.10.0"
