[package]
name = "exercise-rendering-tree"
version = "0.1.0"
authors = ["Takashi Yoneuchi <takashi.yoneuchi@shift-js.info>"]
edition = "2018"

[[bin]]
name = "exercise-rendering-tree"
test = false
bench = false

[dependencies]
combine = "4.5.2"
