name: Manage PR Comment

inputs:
  prNumber:
    required: true
  commentBody:
    required: true
  searchKeyword:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Manage PR Comment
      uses: actions/github-script@v7
      with:
        script: |
          const prNumber = ${{ inputs.prNumber }};
          const commentBody = `${{ inputs.commentBody }}`;
          const searchKeyword = `${{ inputs.searchKeyword }}`;

          const comments = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
          });

          const commentToUpdate = comments.data.find(comment => comment.body.startsWith(searchKeyword));

          if (commentToUpdate) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: commentToUpdate.id,
              body: commentBody,
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: commentBody,
            });
          }
