name: Create Release PR

on:
  pull_request:
    types: [closed]

jobs:
  create_release_pr:
    if: github.event.pull_request.merged && github.event.pull_request.base.ref == 'stage'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Close existing open PRs targeting release branch
        run: |
          gh pr list --state open --base release --json number \
            | jq -r '.[].number' \
            | xargs -I {} gh pr close {} --comment "新しいリリース用 PR を作成するため close します。"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release PR
        run: |
          gh pr create --base release --head stage \
            --title "【release】${{ github.event.pull_request.title }}" \
            --body "stage ブランチにマージされた #${{ github.event.pull_request.number }} に基づいて自動的に作成されました。"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
