{
 "title": "gRPC RED Method",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(grpc_method,grpc_service)(rate(grpc_server_handled_total{}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(grpc_method)(rate(grpc_server_handled_total{grpc_code=~\"(Unknown|Internal)\"}[1m])) / sum by(grpc_method)(rate(grpc_server_handled_total{}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(grpc_server_handling_seconds_sum{}[1m]) / rate(grpc_server_handling_seconds_count{}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}